bumps:
  - file: ./package.json
    regex:
      - pattern: '"version": "$VERSION"'
        semver: true
        count: 1
  - file: ./package-lock.json
    regex:
      - pattern: '"version": "$VERSION"'
        semver: true
        count: 1
