name: 'Uplift Action'
description: 'GitHub Action for Uplift, the semantic versioning tool built for CI'
author: 'gembaadvantage'
branding:
  color: 'blue'
  icon: 'tag'

inputs:
  version:
    description: 'Uplift version'
    default: 'latest'
    required: false
  install-only:
    description: 'If the uplift binary should be installed only'
    default: 'false'
    required: false
  args:
    description: 'List of arguments when running Uplift'
    required: true

runs:
  using: 'node12'
  main: 'dist/index.js'
